In [8]:
import pandas as pd

In [9]:
import pandas as pd

df = pd.read_csv("../Data/final_olist_dataset.csv")

In [10]:
df.to_sql("orders", conn, if_exists="replace", index=False)

118434

In [11]:
query = "SELECT * FROM orders LIMIT 5;"
pd.read_sql(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_time_days,shipping_time_days,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,2.0,...,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,2.0,...,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,2.0,...,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0,1.0,...,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,0.0,...,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0

In [12]:
query = """
SELECT COUNT(*) AS Total_Orders
FROM orders;
"""

pd.read_sql(query, conn)

   Total_Orders
0        118434

In [13]:
query = """
SELECT payment_type,
COUNT(*) AS Total_Orders
FROM orders
GROUP BY payment_type;
"""

pd.read_sql(query, conn)

  payment_type  Total_Orders
0          NaN             3
1       boleto         23037
2  credit_card         87286
3   debit_card          1698
4  not_defined             3
5      voucher          6407

In [14]:
query = """
SELECT AVG(payment_value) AS Avg_Payment
FROM orders;
"""

pd.read_sql(query, conn)

   Avg_Payment
0   172.849395

In [15]:
query = """
SELECT customer_state,
COUNT(*) AS Total_Orders
FROM orders
GROUP BY customer_state
ORDER BY Total_Orders DESC;
"""

pd.read_sql(query, conn)

   customer_state  Total_Orders
0              SP         49967
1              RJ         15420
2              MG         13738
3              RS          6521
4              PR          6017
5              SC          4328
6              BA          4071
7              DF          2489
8              GO          2443
9              ES          2347
10             PE          1894
11             CE          1560
12             MT          1129
13             PA          1122
14             MA           851
15             MS           849
16             PB           643
17             PI           575
18             RN           572
19             AL           460
20             SE           403
21             TO           340
22             RO           292
23             AM           172
24             AC            95
25             AP            84
26             RR            52

In [16]:
query = """
SELECT COUNT(*) AS Delayed_Orders
FROM orders
WHERE delayed = 1;
"""

pd.read_sql(query, conn)

   Delayed_Orders
0            7530

In [17]:
query = """
SELECT customer_state,
AVG(estimated_delay_days) AS Avg_Delay
FROM orders
GROUP BY customer_state
ORDER BY Avg_Delay DESC;
"""

pd.read_sql(query, conn)

   customer_state  Avg_Delay
0              AL  -8.537415
1              MA  -9.876528
2              SE -10.025907
3              ES -10.591678
4              BA -10.991603
5              SP -11.226319
6              MS -11.255090
7              CE -11.279520
8              PI -11.473779
9              SC -11.603599
10             RJ -12.032267
11             DF -12.197852
12             GO -12.277403
13             TO -12.547904
14             PB -13.017657
15             MG -13.357654
16             PE -13.476477
17             PR -13.476653
18             RN -13.686275
19             RS -14.189596
20             PA -14.280734
21             MT -14.396664
22             RR -18.326087
23             AP -18.650602
24             AM -19.857988
25             RO -19.982206
26             AC -21.180851

In [18]:
query = """
SELECT order_id,
payment_value
FROM orders
ORDER BY payment_value DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                           order_id  payment_value
0  03caa2c082116e1d31e67e9ae3700499       13664.08
1  03caa2c082116e1d31e67e9ae3700499       13664.08
2  03caa2c082116e1d31e67e9ae3700499       13664.08
3  03caa2c082116e1d31e67e9ae3700499       13664.08
4  03caa2c082116e1d31e67e9ae3700499       13664.08
5  03caa2c082116e1d31e67e9ae3700499       13664.08
6  03caa2c082116e1d31e67e9ae3700499       13664.08
7  03caa2c082116e1d31e67e9ae3700499       13664.08
8  736e1922ae60d0d6a89247b851902527        7274.88
9  736e1922ae60d0d6a89247b851902527        7274.88

In [19]:
query = """
SELECT order_month,
COUNT(*) AS Total_Orders
FROM orders
GROUP BY order_month;
"""

pd.read_sql(query, conn)

   order_month  Total_Orders
0        April         11135
1       August         12745
2     December          6617
3     February         10068
4      January          9614
5         July         12253
6         June         11209
7        March         11790
8          May         12684
9     November          9111
10     October          6036
11   September          5172

In [20]:
query = """
SELECT AVG(freight_value) AS Avg_Freight
FROM orders;
"""

pd.read_sql(query, conn)

   Avg_Freight
0    20.045551

In [21]:
query = """
SELECT *
FROM orders
WHERE payment_value >
(
SELECT AVG(payment_value)
FROM orders
);
"""

pd.read_sql(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_time_days,shipping_time_days,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,0.0,...,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
1,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01,16.0,1.0,...,147.90,27.36,automotivo,49.0,608.0,1.0,7150.0,65.0,10.0,65.0
2,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07,12.0,1.0,...,99.00,30.53,ferramentas_jardim,36.0,450.0,1.0,9000.0,42.0,12.0,39.0
3,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07,12.0,1.0,...,99.00,30.53,ferramentas_jardim,36.0,450.0,1.0,9000.0,42.0,12.0,39.0
4,403b97836b0c04a622354cf531062e5f,738b086814c6fcc74b8cc583f8516ee3,delivered,2018-01-02 19:00:43,2018-01-02 19:09:04,2018-01-03 18:19:09,2018-01-20 01:38:59,2018-02-06,17.0,0.0,...,1299.00,77.45,construcao_ferramentas_construcao,38.0,143.0,2.0,20850.0,100.0,25.0,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33786,aa04ef5214580b06b10e2a378300db44,f01a6bfcc730456317e4081fe0c9940e,delivered,2017-01-27 00:30:03,2017-01-27 01:05:25,2017-01-30 11:40:16,2017-02-07 13:15:25,2017-03-17,11.0,3.0,...,370.00,19.43,beleza_saude,48.0,657.0,1.0,750.0,38.0,12.0,25.0
33787,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,22.0,1.0,...,174.90,20.10,bebes,52.0,828.0,4.0,4950.0,40.0,10.0,40.0
33788,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,24.0,1.0,...,205.99,65.02,eletrodomesticos_2,51.0,500.0,2.0,13300.0,32.0,90.0,22.0
33789,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,17.0,3.0,...,179.99,40.59,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
33790,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,17.0,3.0,...,179.99,40.59,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0

In [22]:
conn.close()

# SQL Analysis

- Created SQLite database.
- Loaded cleaned dataset into SQLite.
- Executed 10 SQL queries using SELECT, WHERE, GROUP BY, ORDER BY, aggregate functions and a subquery.
- Verified business insights using SQL.